name: ModModePlugin
version: 1.3
main: org.awayxd.modmode.ModModePlugin
api-version: 1.21
commands:
  modmode:
    description: Toggle mod mode.
    usage: /modmode
    permission: modmode.use
  freeze:
    description: Freeze a player.
    usage: /freeze <player>
    permission: modmode.freeze
  unfreeze:
    description: Unfreeze a player.
    usage: /unfreeze <player>
    permission: modmode.unfreeze
permissions:
  modmode.use:
    description: Allows the use of the /modmode command
    default: op
  modmode.freeze:
    description: Allows the use of the /freeze command
    default: op
  modmode.unfreeze:
    description: Allows the use of the /unfreeze command
    default: op
