name: ModModePlugin
version: 1.3
main: org.awayxd.modmode.ModModePlugin
api-version: 1.21
commands:
  modmode:
    description: Enables or disables mod mode
  freeze:
    description: Freezes a player
  unfreeze:
    description: Unfreezes a player
  invsee:
    description: Opens another player's inventory
  staffchat:
    description: Sends a message to the staff chat
  smite:
    description: Smite a player

